FROM node:16-alpine as build-deps
WORKDIR /opt/Anfisa-React-Client/
RUN apk add --no-cache --update \
    git \
    bash
#RUN apk update &&  apk add git bash
RUN cd /opt && git clone https://github.com/ForomePlatform/Anfisa-React-Client.git && \
    cd /opt/Anfisa-React-Client && \
    BRUNCH=$(git branch -r | grep "release-" | sort -r | awk '{print $1}' | head -1 | sed 's|.*/||') && \
    git checkout $BRUNCH
RUN ["yarn", "install"]
RUN ["yarn", "build"]

FROM nginx:latest
RUN rm -Rf /etc/nginx/conf.d/*
COPY --from=build-deps /opt/Anfisa-React-Client/build /usr/share/nginx/html/Anfisa
COPY ./setup/default_front.nginx /etc/nginx/conf.d/front.conf
COPY ./setup/env-config.js /usr/share/nginx/html/Anfisa/env-config.js
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]